from unit import Unit

UNIT_POOL = [
    Unit("Garen", 5, ["God of the Net"]),
    Unit("Zac", 5, ["Virus"]),
    Unit("Viego", 5, ["Soul Killer", "Golden Ox", "Techie"]),
    Unit("Kobuko", 5, ["Cyberboss", "Bruiser"]),
    Unit("Renekton", 5, ["Overlord", "Divinicorp", "Bastion"]),
    Unit("Urgot", 5, ["BoomBot", "Executioner"]),
    Unit("Samira", 5, ["Street Demon", "A.M.P."]),
    Unit("Aurora", 5, ["Anima Squad", "Dynamo"]),
    Unit("Annie", 4, ["Golden Ox", "A.M.P."]),
    Unit("Ziggs", 4, ["Cyberboss", "Strategist"]),
    Unit("Neeko", 4, ["Street Demon", "Strategist"]),
    Unit("Aphelios", 4, ["Golden Ox", "Marksman"]),
    Unit("Sejuani", 4, ["Exotech", "Bastion"]),
    Unit("Xayah", 4, ["Anima Squad", "Marksman"]),
    Unit("Zeri", 4, ["Exotech", "Rapidfire"]),
    Unit("Zed", 4, ["Cypher", "Slayer"]),
    Unit("Leona", 4, ["Anima Squad", "Vanguard"]),
    Unit("Brand", 4, ["Street Demon", "Techie"]),
    Unit("Miss Fortune", 4, ["Syndicate", "Dynamo"]),
    Unit("Cho'Gath", 4, ["BoomBot", "Bruiser"]),
    Unit("Vex", 4, ["Divinicorp", "Executioner"]),
    Unit("Jarvan IV", 3, ["Golden Ox", "Vanguard", "Slayer"]),
    Unit("Gragas", 3, ["Divinicorp", "Bruiser"]),
    Unit("Morgana", 3, ["Divinicorp", "Dynamo"]),
    Unit("Rengar", 3, ["Street Demon", "Executioner"]),
    Unit("Senna", 3, ["Divinicorp", "Slayer"]),
    Unit("Varus", 3, ["Exotech", "Executioner"]),
    Unit("Jinx", 3, ["Street Demon", "Marksman"]),
    Unit("Mordekaiser", 3, ["Exotech", "Bruiser", "Techie"]),
    Unit("Elise", 3, ["Nitro", "Dynamo"]),
    Unit("Fiddlesticks", 3, ["BoomBot", "Techie"]),
    Unit("Galio", 3, ["Cypher", "Bastion"]),
    Unit("Draven", 3, ["Cypher", "Rapidfire"]),
    Unit("Braum", 3, ["Syndicate", "Vanguard"]),
    Unit("Yuumi", 3, ["Anima Squad", "A.M.P.", "Strategist"]),
    Unit("Darius", 2, ["Syndicate", "Bruiser"]),
    Unit("Ekko", 2, ["Street Demon", "Strategist"]),
    Unit("Graves", 2, ["Golden Ox", "Executioner"]),
    Unit("Illaoi", 2, ["Anima Squad", "Bastion"]),
    Unit("Jhin", 2, ["Exotech", "Marksman", "Dynamo"]),
    Unit("LeBlanc", 2, ["Cypher", "Strategist"]),
    Unit("Naafiri", 2, ["Exotech", "A.M.P."]),
    Unit("Rhaast", 2, ["Divinicorp", "Vanguard"]),
    Unit("Shyvana", 2, ["Nitro", "Bastion", "Techie"]),
    Unit("Skarner", 2, ["BoomBot", "Vanguard"]),
    Unit("Twisted Fate", 2, ["Syndicate", "Rapidfire"]),
    Unit("Vayne", 2, ["Anima Squad", "Slayer"]),
    Unit("Veigar", 2, ["Cyberboss", "Techie"]),
    Unit("Zyra", 2, ["Street Demon", "Techie"]),
    Unit("Alistar", 1, ["Golden Ox", "Bruiser"]),
    Unit("Dr. Mundo", 1, ["Street Demon", "Bruiser", "Slayer"]),
    Unit("Jax", 1, ["Exotech", "Bastion"]),
    Unit("Kindred", 1, ["Nitro", "Rapidfire", "Marksman"]),
    Unit("Kog'Maw", 1, ["BoomBot", "Rapidfire"]),
    Unit("Morgana", 1, ["Divinicorp", "Dynamo"]),
    Unit("Nidalee", 1, ["Nitro", "A.M.P."]),
    Unit("Poppy", 1, ["Cyberboss", "Bastion"]),
    Unit("Seraphine", 1, ["Anima Squad", "Techie"]),
    Unit("Shaco", 1, ["Syndicate", "Slayer"]),
    Unit("Sylas", 1, ["Anima Squad", "Vanguard"]),
    Unit("Vi", 1, ["Cypher", "Vanguard"]),
    Unit("Ziggs", 1, ["Cyberboss", "Strategist"]),
    Unit("Zyra", 1, ["Street Demon", "Techie"]),
]

UNIT_DICT = {unit.name: unit for unit in UNIT_POOL}
