from unit import Unit

UNIT_POOL = [
    Unit("Aurelion Sol", 7, ["Star Forger", "Targon"]),
    Unit("Baron Nashor", 7, ["Void", "Riftscourge"]),
    Unit("Brock", 7, ["Ixtal"]),
    Unit("Ryze", 7, ["Rune Mage"]),
    Unit("Sylas", 7, ["Chainbreaker", "Arcanist", "Defender"]),
    Unit("Zaahen", 7, ["Darkin", "Immortal"]),
    Unit("Aatrox", 5, ["Darkin", "World Ender", "Slayer"]),
    Unit("Annie", 5, ["Dark Child", "Arcanist"]),
    Unit("Azir", 5, ["Shurima", "Emperor", "Disruptor"]),
    Unit("Fiddlesticks", 5, ["Harvester", "Vanquisher"]),
    Unit("Galio", 5, ["Demacia", "Heroic"]),
    Unit("Kindred", 5, ["Eternal", "Quickstriker"]),
    Unit("Lucian & Senna", 5, ["Soulbound", "Gunslinger"]),
    Unit("Mel", 5, ["Noxus", "Disruptor"]),
    Unit("Ornn", 5, ["Blacksmith", "Warden"]),
    Unit("Sett", 5, ["Ionia", "The Boss"]),
    Unit("Shyvana", 5, ["Dragonborn", "Juggernaut"]),
    Unit("Tahm Kench", 5, ["Bilgewater", "Glutton", "Bruiser"]),
    Unit("T-Hex", 5, ["HexMech", "Piltover", "Gunslinger"]),
    Unit("Thresh", 5, ["Shadow Isles", "Warden"]),
    Unit("Tibbers", 5, ["Arcanist"]),
    Unit("Volibear", 5, ["Freljord", "Bruiser"]),
    Unit("Xerath", 5, ["Shurima", "Ascendant"]),
    Unit("Ziggs", 5, ["Zaun", "Yordle", "Longshot"]),
    Unit("Zilean", 5, ["Chronokeeper", "Invoker"]),
    Unit("Ambessa", 4, ["Noxus", "Vanquisher"]),
    Unit("Bel'Veth", 4, ["Void", "Slayer"]),
    Unit("Braum", 4, ["Freljord", "Warden"]),
    Unit("Diana", 4, ["Targon"]),
    Unit("Fizz", 4, ["Bilgewater", "Yordle"]),
    Unit("Garen", 4, ["Demacia", "Defender"]),
    Unit("Kai'Sa", 4, ["Assimilator", "Void", "Longshot"]),
    Unit("Kalista", 4, ["Shadow Isles", "Vanquisher"]),
    Unit("Lissandra", 4, ["Freljord", "Invoker"]),
    Unit("Lux", 4, ["Demacia", "Arcanist"]),
    Unit("Miss Fortune", 4, ["Bilgewater", "Gunslinger"]),
    Unit("Nasus", 4, ["Shurima"]),
    Unit("Nidalee", 4, ["Ixtal", "Huntress"]),
    Unit("Renekton", 4, ["Shurima"]),
    Unit("Rift Herald", 4, ["Void", "Bruiser"]),
    Unit("Seraphine", 4, ["Piltover", "Disruptor"]),
    Unit("Singed", 4, ["Zaun", "Juggernaut"]),
    Unit("Skarner", 4, ["Ixtal"]),
    Unit("Swain", 4, ["Noxus", "Arcanist", "Juggernaut"]),
    Unit("Taric", 4, ["Targon"]),
    Unit("Veigar", 4, ["Yordle", "Arcanist"]),
    Unit("Warwick", 4, ["Zaun", "Quickstriker"]),
    Unit("Wukong", 4, ["Ionia", "Bruiser"]),
    Unit("Yone", 4, ["Ionia", "Slayer"]),
    Unit("Yunara", 4, ["Ionia", "Quickstriker"]),
    Unit("Ahri", 3, ["Ionia", "Arcanist"]),
    Unit("Darius", 3, ["Noxus", "Defender"]),
    Unit("Draven", 3, ["Noxus", "Quickstriker"]),
    Unit("Dr. Mundo", 3, ["Zaun", "Bruiser"]),
    Unit("Gangplank", 3, ["Bilgewater", "Slayer", "Vanquisher"]),
    Unit("Gwen", 3, ["Shadow Isles", "Disruptor"]),
    Unit("Jinx", 3, ["Zaun", "Gunslinger"]),
    Unit("Kennen", 3, ["Ionia", "Yordle", "Defender"]),
    Unit("Kobuko & Yummi", 3, ["Yordle", "Bruiser", "Invoker"]),
    Unit("LeBlanc", 3, ["Noxus", "Invoker"]),
    Unit("Leona", 3, ["Targon"]),
    Unit("Loris", 3, ["Piltover", "Warden"]),
    Unit("Malzahar", 3, ["Void", "Disruptor"]),
    Unit("Milio", 3, ["Ixtal", "Invoker"]),
    Unit("Nautilus", 3, ["Bilgewater", "Juggernaut", "Warden"]),
    Unit("Sejuani", 3, ["Freljord", "Defender"]),
    Unit("Vayne", 3, ["Demacia", "Longshot"]),
    Unit("Zoe", 3, ["Targon"]),
    Unit("Aphelios", 2, ["Targon"]),
    Unit("Ashe", 2, ["Freljord", "Quickstriker"]),
    Unit("Bard", 2, ["Caretaker"]),
    Unit("Cho'Gath", 2, ["Void", "Juggernaut"]),
    Unit("Ekko", 2, ["Zaun", "Disruptor"]),
    Unit("Graves", 2, ["Bilgewater", "Gunslinger"]),
    Unit("Neeko", 2, ["Ixtal", "Arcanist", "Defender"]),
    Unit("Orianna", 2, ["Piltover", "Invoker"]),
    Unit("Poppy", 2, ["Demacia", "Yordle", "Juggernaut"]),
    Unit("Rek'Sai", 2, ["Void", "Vanquisher"]),
    Unit("Sion", 2, ["Noxus", "Bruiser"]),
    Unit("Teemo", 2, ["Yordle", "Longshot"]),
    Unit("Tristana", 2, ["Yordle", "Gunslinger"]),
    Unit("Tryndamere", 2, ["Freljord", "Slayer"]),
    Unit("Twisted Fate", 2, ["Bilgewater", "Quickstriker"]),
    Unit("Vi", 2, ["Piltover", "Zaun", "Defender"]),
    Unit("Xin Zhao", 2, ["Demacia", "Ionia", "Warden"]),
    Unit("Yasuo", 2, ["Ionia", "Slayer"]),
    Unit("Yorick", 2, ["Shadow Isles", "Warden"]),
    Unit("Anivia", 1, ["Freljord", "Invoker"]),
    Unit("Blitzcrank", 1, ["Zaun", "Juggernaut"]),
    Unit("Briar", 1, ["Noxus", "Slayer", "Juggernaut"]),
    Unit("Caitlyn", 1, ["Piltover", "Longshot"]),
    Unit("Illaoi", 1, ["Bilgewater", "Bruiser"]),
    Unit("Jarvan IV", 1, ["Demacia", "Defender"]),
    Unit("Jhin", 1, ["Ionia", "Gunslinger"]),
    Unit("Kog'Maw", 1, ["Void", "Arcanist", "Longshot"]),
    Unit("Lulu", 1, ["Yordle", "Arcanist"]),
    Unit("Qiyana", 1, ["Ixtal", "Slayer"]),
    Unit("Rumble", 1, ["Yordle", "Defender"]),
    Unit("Shen", 1, ["Ionia", "Bruiser"]),
    Unit("Sona", 1, ["Demacia", "Invoker"]),
    Unit("Viego", 1, ["Shadow Isles", "Quickstriker"])
]

UNIT_DICT = {unit.name: unit for unit in UNIT_POOL}
